# Generated by Django 4.0.6 on 2022-08-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmittedanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='usersubmittedanswer',
            name='submitted_ans',
        ),
    ]
